"""Initial migration

Revision ID: a539a4336ede
Revises: 
Create Date: 2025-02-01 13:24:28.137901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a539a4336ede'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'office_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'wallet_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('office_name', table_name='users')
    op.drop_index('wallet_address', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_office_name'), 'users', ['office_name'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_office_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('wallet_address', 'users', ['wallet_address'], unique=True)
    op.create_index('office_name', 'users', ['office_name'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'wallet_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'office_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
